
version: '3.8'

services:
  # ---------------------------
  # Microservice client-api
  # ---------------------------
  client-api:
    build: .                        # Dockerfile dans le même dossier
    image: payetonkawa-client-api
    container_name: client-api
    ports:
      - "8081:8081"
    depends_on:
      - postgresdb
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/clientdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_RABBITMQ_HOST: rabbitmq

  # ---------------------------
  # PostgreSQL
  # ---------------------------
  postgresdb:
    image: postgres:13
    container_name: client-api-postgresdb
    environment:
      POSTGRES_DB: clientdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"   # port externe 5433 pour éviter conflit avec un Postgres local
    volumes:
      - clientdb_data:/var/lib/postgresql/data
    restart: unless-stopped
  
  # ---------------------------
  # RabbitMQ
  # ---------------------------
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: client-api-rabbitmq
    ports:
      - "5673:5672"     
      - "15673:15672"   
    restart: unless-stopped

# ---------------------------
# Volumes pour persistance
# ---------------------------
volumes:
  clientdb_data:
